# Assignment - Index splitting (take home)

1. Create an array of shape (100,100,3) of unsigned integer 8 bits filled with random values between 0 to 256.
2. Find the values that are less than 30, 50, 100, 250.
3. Split the array into 4 parts vertically and horizontally
4. Copy array from Question 1 and change the values that are les than 110 to 0 and others to 255
5. Hint: Use random seed of 12345

In [1]:
# 1. Create an array of shape (100,100,3) of unsigned integer 8 bits filled with random values between 0 to 256
import numpy as np

np.random.seed(12345)
a = np.random.randint(0, 256, (100, 100, 3), dtype = 'uint8')


In [2]:
# 2. Find the values that are less than 30, 50, 100, 250.

# To print full array in output, change threshold=np.inf. Default is threshold=1000 
np.set_printoptions(threshold=1000)

a_30 = a < 30
print('Values less than 30:\n', a[a_30])

a_50 = a < 50
print('\nValues less than 50:\n', a[a_50])

a_100 = a < 100
print('\nValues less than 100:\n', a[a_100])

a_250 = a < 250
print('\nValues less than 250:\n', a[a_250])

Values less than 30:
 [29  8 21 ...  5 28 24]

Values less than 50:
 [45 29  8 ... 35 24 46]

Values less than 100:
 [81 45 29 ... 75 24 46]

Values less than 250:
 [226  81 237 ... 156 214 199]


In [3]:
# 3. Split the array into 4 parts vertically horizontally

# .hsplit and .vsplit will return a list containing the splitted array as the list's element
a4h = np.hsplit(a,4)
print('Array element in horizontaly splitted array:',len(a4h))

a4v = np.vsplit(a,4)
print('Array element in vertically splitted array:',len(a4h))

# If splitted into 5 parts, the array element inside the list will be 5 elements
a5h = np.hsplit(a,5)
print('\nArray element in horizontaly splitted array:',len(a5h))

Array element in horizontaly splitted array: 4
Array element in vertically splitted array: 4

Array element in horizontaly splitted array: 5


In [4]:
# 4. Copy array from Question 1 and change the values that are less than 110 to 0 and others to 255

b = a.copy()

# Call numpy.where(condition, x, y) to replace values that meet condition with x, and those that do not with y.
b_new = np.where(b < 110, 0, 255) 

print(b_new)

[[[255   0 255]
  [255 255   0]
  [255 255   0]
  ...
  [255 255 255]
  [255 255 255]
  [  0   0   0]]

 [[  0 255 255]
  [255   0 255]
  [  0 255   0]
  ...
  [  0 255 255]
  [  0 255 255]
  [255   0   0]]

 [[255   0 255]
  [  0   0 255]
  [  0 255   0]
  ...
  [  0 255 255]
  [255   0   0]
  [255 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [  0   0   0]
  ...
  [255   0 255]
  [  0 255 255]
  [255   0   0]]

 [[255   0 255]
  [255   0   0]
  [255 255 255]
  ...
  [255 255   0]
  [  0   0 255]
  [  0 255 255]]

 [[255 255   0]
  [  0 255   0]
  [  0 255 255]
  ...
  [255 255   0]
  [255 255 255]
  [255 255 255]]]
